# Configuration file to test new code -> it runs a small number of episodes to test
# that the code runs without errors

label: "" # If left empty, it will be created automatically based on config

runner: "episode" # Runs x env for an episode
batch_size_run: 1 # Number of environments to run in parallel
batch_size: 32 # Number of episodes to train on
buffer_size: 500 # Size of the replay buffer 5000:qmix, 8:coma
algorithm: "qmix" 
env: "sc2" 

env_args:
  map_name: "8m"
  debug: False

transfer: True # If true, transfer learning is used
tl_args:
  single_source: True # If true, only one source is used for transfer learning
  source_maps: ["baselines/3m_rnn_qmix"] # Maps to use for transfer learning
  method: "direct_unfreeze" # direct, direct_unfreeze
  unfreeze_percentage_training: 100.0 # Percentage of the epsilon anneal time to unfreeze the model
  policy_distillation: "mean" # defines how different weights are combined

pad_input: False # If true, input is padded before RNN
pad_size: 512 # Greater than any state vector size

epsilon_exp: True
epsilon_start: 0.5 # 1:qmix, .5:coma
epsilon_finish: 0.05 # 0.05:qmix, .01:coma
epsilon_anneal_time: 50000 # 50000:qmix, 100000:coma

t_max: 2050000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

test_nepisode: 32 # Number of episodes to test for
test_interval: 10000 # Test after {} timesteps have passed

log_interval: 10000 # Log summary of stats after every {} timesteps
runner_log_interval: 10000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 10000 # Log training stats every {} timesteps

# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 100000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

### Usually kept as default
mac: "basic_mac" # Basic controller

# --- RL hyperparameters ---
gamma: 0.99
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation
