# Research configuration file -> it includes those parameters more relevant
# to the research process

runner: "parallel" # Runs x env for an episode
batch_size_run: 8 # Number of environments to run in parallel
batch_size: 32 # Number of episodes to train on
algorithm: "qmix" 
env: "sc2" 

env_args:
  map_name: "3m"
  debug: False

t_max: 2050000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available

test_nepisode: 32 # Number of episodes to test for
test_interval: 10000 # Test after {} timesteps have passed

log_interval: 10000 # Log summary of stats after every {} timesteps
runner_log_interval: 10000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 10000 # Log training stats every {} timesteps

# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 200000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

### Usually kept as default
mac: "basic_mac" # Basic controller

# --- RL hyperparameters ---
gamma: 0.99
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation