# --- COMA specific parameters ---

action_selector: "multinomial" # default multinomial
mask_before_softmax: False

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 150 # def: 200, but in paper they do every 150

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "coma"
